### ISSUE TITLE
https://github.com/SeleniumHQ/selenium/issues/11750#issuecomment-1470532188

### ISSUE THREAD

**Issue by thonypr** [rabelenda/onyx-scheduler#5]
hi!

sorry for writing here, but did you happen to find solution for chrome 111 version on selenium?

https://github.com/SeleniumHQ/selenium/issues/11750#issuecomment-1470532188

**Comment by rabelenda** [comment]
Hello, I basically stopped using the debuggerAddress address option, and changed the way I tested what I wanted to test. I haven't tried since the 4.9.0 release if such test would work with debuggerAddress again.

**Comment by thonypr** [comment]
thanks anyway!> Hello, I basically stopped using the debuggerAddress address option, and changed the way I tested what I wanted to test. I haven't tried since the 4.9.0 release if such test would work with debuggerAddress again.
